### ISSUE TITLE
Getting errors on certain files after the new update

### ISSUE THREAD

**Issue by ZayRTun** [EmranMR/tree-sitter-blade#40]
I want to express my appreciation to Emran Ramezan and Yaegassy for this Treesitter parser for Laravel Blade. I've been enjoying it a lot, but since the latest update yesterday, I've encountered some errors. It seems to work well on certain Blade files, but on others, I'm facing issues.

I am using it with LazyVim. I am not sure whether it is due tree sitter update or some other plugin. I have also followed the upgrade guide to set up `injections.scm` file. 

### Screenshot of the file where I get the error:
![Screenshot 2023-12-04 at 19 08 42](https://github.com/EmranMR/tree-sitter-blade/assets/31787822/f5adc18f-f3e1-42e9-a6ad-01fe485cfde6)

### Screenshot of the file where there is no error:
![Screenshot 2023-12-04 at 19 08 02](https://github.com/EmranMR/tree-sitter-blade/assets/31787822/4a17604a-f57d-4920-b672-9368960c91ca)

### Error message
```console
[Neo-tree ERROR] Error opening file: vim/_editor.lua:0: nvim_exec2()..BufReadPost Autocommands for "*": Vim(append):Error executing lua callback: ...brew/Cellar/neovim/0.9.1/share/nvim/runtime/filetype.lua:21: Error executing lua: ...brew/Cellar/neovim/0.9.1/share/nvim/runtime/filetype.lua:22: nvim_exec2()..BufReadPost Autocommands for "*"..FileType Autocommands for "*": Vim(append):Error executing lua callback: ...1/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:260: Ranges can only be made from 6 element long tables or nodes.
stack traceback:
	[C]: in function 'set_included_ranges'
	...1/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:260: in function 'parse'
	...1/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:312: in function 'fn'
	...1/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:326: in function 'for_each_child'
	...1/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:330: in function 'for_each_child'
	...1/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:311: in function 'parse'
	...r/neovim/0.9.1/share/nvim/runtime/lua/vim/treesitter.lua:89: in function '_create_parser'
	...r/neovim/0.9.1/share/nvim/runtime/lua/vim/treesitter.lua:131: in function 'get_parser'
	...r/neovim/0.9.1/share/nvim/runtime/lua/vim/treesitter.lua:459: in function 'start'
	...m/lazy/nvim-treesitter/lua/nvim-treesitter/highlight.lua:20: in function 'attach'
	...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:509: in function 'attach_module'
	...
	[C]: in function 'nvim_buf_call'
	...brew/Cellar/neovim/0.9.1/share/nvim/runtime/filetype.lua:21: in function <...brew/Cellar/neovim/0.9.1/share/nvim/runtime/filetype.lua:10>
	[C]: in function 'nvim_exec2'
	vim/_editor.lua: in function <vim/_editor.lua:0>
	[C]: in function 'pcall'
	...hare/nvim/lazy/neo-tree.nvim/lua/neo-tree/utils/init.lua:714: in function 'open_file'
	...y/neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:729: in function 'open'
	...y/neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:751: in function 'open_with_cmd'
	...y/neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:760: in function 'open'
	...o-tree.nvim/lua/neo-tree/sources/filesystem/commands.lua:184: in function <...o-tree.nvim/lua/neo-tree/sources/filesystem/commands.lua:183>
stack traceback:
	[C]: in function 'nvim_cmd'
	...brew/Cellar/neovim/0.9.1/share/nvim/runtime/filetype.lua:22: in function <...brew/Cellar/neovim/0.9.1/share/nvim/runtime/filetype.lua:21>
	[C]: in function 'nvim_buf_call'
	...brew/Cellar/neovim/0.9.1/share/nvim/runtime/filetype.lua:21: in function <...brew/Cellar/neovim/0.9.1/share/nvim/runtime/filetype.lua:10>
	[C]: in function 'nvim_exec2'
	vim/_editor.lua: in function <vim/_editor.lua:0>
	[C]: in function 'pcall'
	...hare/nvim/lazy/neo-tree.nvim/lua/neo-tree/utils/init.lua:714: in function 'open_file'
	...y/neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:729: in function 'open'
	...y/neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:751: in function 'open_with_cmd'
	...y/neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:760: in function 'open'
	...o-tree.nvim/lua/neo-tree/sources/filesystem/commands.lua:184: in function <...o-tree.nvim/lua/neo-tree/sources/filesystem/commands.lua:183>
stack traceback:
	[C]: in function 'nvim_buf_call'
	...brew/Cellar/neovim/0.9.1/share/nvim/runtime/filetype.lua:21: in function <...brew/Cellar/neovim/0.9.1/share/nvim/runtime/filetype.lua:10>
	[C]: in function 'nvim_exec2'
	vim/_editor.lua: in function <vim/_editor.lua:0>
	[C]: in function 'pcall'
	...hare/nvim/lazy/neo-tree.nvim/lua/neo-tree/utils/init.lua:714: in function 'open_file'
	...y/neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:729: in function 'open'
	...y/neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:751: in function 'open_with_cmd'
	...y/neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:760: in function 'open'
	...o-tree.nvim/lua/neo-tree/sources/filesystem/commands.lua:184: in function <...o-tree.nvim/lua/neo-tree/sources/filesystem/commands.lua:183>
```

**Comment by ZayRTun** [comment]
Hi @EmranMR, thanks for the response

I tried your suggestion by removing `php_only` part from `injections.scm` but still getting the error. I also tried downgrading 'nvim-treesitter` thinking maybe that's the reason, but it was the same.

And yeah, both the screenshots above are using `v0.9.0`

### Another screenshot just for you reference, both files are almost the same
![Screenshot 2023-12-04 at 21 51 06](https://github.com/EmranMR/tree-sitter-blade/assets/31787822/aa3a5763-f5fc-4e3b-ba03-44bac16b7af6)

**Comment by EmranMR** [comment]
@ZayRTun thats so strange😬

can you do me a favour and drop the entire code excerpt from the file that is not working? so that I can copy and paste, to run some tests using the `cli` and give it a shot with Nova. 

After that I could tell you for certain if it's the neovim, or it's config acting up or the parser, `tree-sitter-blade` itself!

**Comment by ZayRTun** [comment]
@EmranMR I just tested with `v0.9.1` and it's working across all files without any issues. Thanks for fixing this.

**Comment by ZayRTun** [comment]
@EmranMR I think i found a small little issue. Highlighting goes off after `{{ $attributes->wire('model') }} ` such attributes. Just letting you know. 

### With the `{{ $attributes->wire('model') }} `
![Screenshot 2023-12-05 at 09 37 08](https://github.com/EmranMR/tree-sitter-blade/assets/31787822/8b6fa647-baf6-4f7b-8427-67d260e9b615)

### Without the `{{ $attributes->wire('model') }} `
![Screenshot 2023-12-05 at 09 37 28](https://github.com/EmranMR/tree-sitter-blade/assets/31787822/0b4b4610-a7f6-4770-ae44-5e240a3cb8fa)

### Code snippet
```blade
<div {{ $attributes->class([]) }}>
    <label for="search" class="block  font-medium text-gray-700 sr-only">Search</label>

    <div class="relative">
        <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
            <svg class="h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd" />
            </svg>
        </div>

        <input {{ $attributes->wire('model') }} type="text" name="search" id="search"
               autocomplete="off"
               class="focus:ring-yellow-300 focus:border-yellow-300 block w-full pl-10  border-gray-300 rounded-md"
               placeholder="{{ $placeholder }}">
    </div>
</div>
```

**Comment by EmranMR** [comment]
@ZayRTun That does not seem to be an issue with `tree-sitter-blade` by the looks of it. There were no errors parsing your code using `cli`, and Nova seem to be functioning fine, picking up everything as well, **but** I got some insights for you!

### Nova With Blade turned on
 
<img width="2672" alt="Screenshot 2023-12-05 at 09 02 01" src="https://github.com/EmranMR/tree-sitter-blade/assets/11975985/d8da3dc1-aea4-413b-8c8c-28a17c89433f">

### Nova with `tree-sitter-blade` turned off. 

- The following is the code editor, with `html` **chosen** as the syntax for the document, **_NOT_** the blade (as if it is `.php` or `.html`)

<img width="1451" alt="Screenshot 2023-12-05 at 09 03 31" src="https://github.com/EmranMR/tree-sitter-blade/assets/11975985/1c086fe4-8852-4076-868a-f644a9858451">


### How to fix?
It seems there is certainly something wrong with your NeoVim config or how it is installed, quite strange the issue started after the update though!
Maybe head over to the [NeoVim installation discussion](https://github.com/EmranMR/tree-sitter-blade/discussions/19), **reference this issue** and see if anyone can help? Unfortunately, I am not a NeoVim user myself, so all I can do is to just debug using cli and Nova 😬

**Comment by EmranMR** [comment]
Maybe the configuration picking `.php` as syntax instead of `.blade.php`?

**Comment by ZayRTun** [comment]
@EmranMR I will look into this like you said, maybe there is something wrong with my lazyvim setup, I am not sure. But anyway thanks to you for all this, been using ur tree sitter the whole day without any issue.

**Comment by EmranMR** [comment]
@ZayRTun definitely keep me posted here and do let us know if you managed to find the root of the problem! Would be interesting to know for future reference!

**Comment by ZayRTun** [comment]
@EmranMR I have been checking out treesitter query, and one thing I noticed is that the parser is detecting blade comment `{{-- comment --}}` as text but if it's an HTML comments are detected as comment. These both comments are in the same blade file, I have also checked the detected file type and it shows as `blade`.

Oh, and btw I am using the latest v0.9.2 version. 

### blade comment
![Screenshot 2023-12-07 at 00 19 38](https://github.com/EmranMR/tree-sitter-blade/assets/31787822/85e4762f-da37-4084-8282-b97c2fcf7422)

### HTML comment
![Screenshot 2023-12-07 at 00 18 43](https://github.com/EmranMR/tree-sitter-blade/assets/31787822/cdec599e-c390-459d-af5c-bb8c75425fff)

**Comment by ZayRTun** [comment]
@EmranMR Below is what I am getting. It seems that it's being picked as comment in this blade file...

```blade
<html>
    @php
        echo 'test';
    @endphp

    {{-- <div>{{echo "test"}</div> --}}
</html>
```

```
(element) ; [1:1 - 7:7]
 (start_tag) ; [1:1 - 6]
  (tag_name) ; [1:2 - 5]
 (text) ; [2:5 - 6:8]
 (element) ; [6:10 - 34]
  (start_tag) ; [6:10 - 14]
   (tag_name) ; [6:11 - 13]
  (text) ; [6:15 - 28]
  (end_tag) ; [6:29 - 34]
   (tag_name) ; [6:31 - 33]
 (text) ; [6:36 - 39]
 (end_tag) ; [7:1 - 7]
  (tag_name) ; [7:3 - 6]
(text) ; [1:1 - 2:4]
(php_statement) ; [2:5 - 4:11]
 (directive_start) ; [2:5 - 8]
 (php_only) ; [3:9 - 4:4]
 (directive_end) ; [4:5 - 11]
(comment) ; [6:5 - 39]
(text) ; [7:1 - 8:0]
```

### my `nvim-treesitter` setup
```lua
return {
    "nvim-treesitter/nvim-treesitter",
    opts = function(_, opts)
        vim.list_extend(opts.ensure_installed, {
            "css",
            "http",
            "markdown",
            "php",
            "phpdoc",
            "rust",
            "vue",
        })
    end,

    config = function(_, opts)
        require("nvim-treesitter.configs").setup(opts)

        ---@class parser_config
        local parser_config = require("nvim-treesitter.parsers").get_parser_configs()
        parser_config.blade = {
            install_info = {
                url = "https://github.com/EmranMR/tree-sitter-blade",
                files = { "src/parser.c" },
                branch = "main",
            },
            filetype = "blade",
        }

        vim.filetype.add({
            pattern = {
                [".*%.blade%.php"] = "blade",
            },
        })
    end,
}
```

**Comment by EmranMR** [comment]
@ZayRTun Mmm that is so strange, so it is basically works when it wants.

I I would just dump the config in the discussion below and reference back to this issue. I am sure someone more seasoned with NeoVim would be able to help out.
> Maybe head over to the [NeoVim tree-sitter-blade installation discussion]( https://github.com/EmranMR/tree-sitter-blade/discussions/19)

With regards to:
>Also when ever I insert a comment it always insert html comment , to get blade comment I have to insert them manually.

This is the [same case with Nova #18 ](https://github.com/EmranMR/Laravel-Nova-Extension/issues/18). So it might actually be a `tree-sitter` thing in general I suppose.

**Comment by calebdw** [comment]
> Also when ever I insert a comment it always insert html comment , to get blade comment I have to insert them manually.

This is expected if you're using treesitter based commenting---the reason is that most of the time you're going to be in an html node instead of a blade node since most of the file is html
