### ISSUE TITLE
[QUESTION]: what highlighting to expect

### ISSUE THREAD

**Issue by itsmenewbie03** [EmranMR/tree-sitter-blade#63]
This is the current highlighting that I have.
What did I miss?
![image](https://github.com/EmranMR/tree-sitter-blade/assets/89230263/93718980-6832-402c-ac80-fe97a55b226f)

**Comment by calebdw** [comment]
Probably have not installed the bash parser

**Comment by itsmenewbie03** [comment]
> Probably have not installed the bash parser

I have it installed
![image](https://github.com/EmranMR/tree-sitter-blade/assets/89230263/609cd277-eac4-4089-a456-baef30d02873)

**Comment by calebdw** [comment]
What do your highlight queries look like?

**Comment by itsmenewbie03** [comment]
turns out I just had to read more carefully xD
I just needed to `:TSInstall php_only`
![image](https://github.com/EmranMR/tree-sitter-blade/assets/89230263/7b60f83e-69cb-497b-90fc-3c330170c30f)
