### ISSUE TITLE
[QUESTION] Support for Livewire Volt Components

### ISSUE THREAD

**Issue by greg-grigorjevs** [EmranMR/tree-sitter-blade#64]
Hi, I am using livewire Volt class based components.

Here's how the highlighting looks like when the filetype is set to blade:
<img width="1057" alt="Screenshot 2024-04-07 at 12 46 50" src="https://github.com/EmranMR/tree-sitter-blade/assets/69362855/b71edbd7-dbca-4cc3-b16f-fad58081c867">

And here how it looks like when the filetype is set to php:
<img width="1122" alt="Screenshot 2024-04-07 at 12 47 25" src="https://github.com/EmranMR/tree-sitter-blade/assets/69362855/2bc19ab4-9fb3-4d3e-8c1d-ce1c46dfb204">

I would like to know if there is a way to extend the blade/injections.scm file in a way so that:
- the code inside `<?php ?>`  has the same highlighting as when the filetype is set to php 
- the code bellow has the sage highlighting as when the filetype is set to blade 

Thank you

**Comment by EmranMR** [comment]
Hi, can I have the code excerpt? 

The injection and highlighting are all taken care of by `tree-sitter-php` and `tree-sitter-php_only`. So technically the syntax highlighting should be the same.

Unless of course there are parsing error by `tree-sitter-blade` which I can have a look.

**Comment by EmranMR** [comment]
I'll close this issue for now as it appears to be stale. However, please feel free to reopen it if the problem persists.
