### ISSUE TITLE
How to select a tree in double tree?

### ISSUE THREAD

**Issue by RicardoRamirezR** [EmranMR/tree-sitter-blade#67]
Hi there,

From #47 

```blade
<x-settings.nav-link href="{{ route('bookings.stats.by.pet') }}">Speaks</x-settings.nav-link>
____________________________^
```
The `_^` is the cursor position.

Using:
```lua
local current_node = ts_utils.get_node_at_cursor()
print(func:type())
```
prints `attribute_value` in:

<img width="1466" alt="Screenshot 2024-07-25 at 8 22 01 AM" src="https://github.com/user-attachments/assets/04018976-ac34-4d83-bb9d-587ba0090de6">  

Question: how to use the blade tree instead of html one?

**Comment by EmranMR** [comment]
I am not sure why why that is not working out, it seems to be working for me in Helix. The only issue I have is the Tag Name #62 , which I am yet to tackle, I have some ideas on how to fix it though ;)

<img width="1064" alt="image" src="https://github.com/user-attachments/assets/12e9f73c-2c26-4b36-aaf9-be63116205c9">

**Comment by calebdw** [comment]
The `html` is an injected language---whatever api you are using should allow you to get the uninjected vs injected tree

**Comment by RicardoRamirezR** [comment]
@calebdw indeed, `ignore_injected_langs` did the trick
