### ISSUE TITLE
PHP highlight not work, but installed

### ISSUE THREAD

**Issue by brunojoao** [EmranMR/tree-sitter-blade#73]
![image](https://github.com/user-attachments/assets/897bed79-b9e3-4c8b-92db-628fdea58a4b)

TSInstall php blade

**highlights.scm**
(directive) @function
(directive_start) @function
(directive_end) @function
(comment) @comment
((parameter) @include (#set! "priority" 110)) 
((php_only) @include (#set! "priority" 110)) 
((bracket_start) @function (#set! "priority" 120)) 
((bracket_end) @function (#set! "priority" 120)) 
(keyword) @function

**injections.scm**
((text) @injection.content
    (#not-has-ancestor? @injection.content "envoy")
    (#set! injection.combined)
    (#set! injection.language php))

; could be bash or zsh
; or whatever tree-sitter grammar you have.
((text) @injection.content
    (#has-ancestor? @injection.content "envoy")
    (#set! injection.combined)
    (#set! injection.language bash))

css, javacript works, but php not

**inspectTree:**
![image](https://github.com/user-attachments/assets/371823fa-e5ed-48d8-87c5-46122e2899fd)

**Comment by calebdw** [comment]
You probably haven't installed the `php_only` parser

**Comment by brunojoao** [comment]
![image](https://github.com/user-attachments/assets/b30a310c-9971-40e9-a48b-448374f2a949)

i try, but not works

**Comment by brunojoao** [comment]
now works, missing step 3, thx 

((php_only) @injection.content
   (#set! injection.language php_only))
