### ISSUE TITLE
Issue with the parser

### ISSUE THREAD

**Issue by Th3Cod3** [EmranMR/tree-sitter-blade#79]
Hi guy's, I'm trying to use this tree-sitter, but I'm getting some parse issue (I guess is a parser issue). I leave a screenshot of the `InpectionTree` and code. 

parser.c commit #4ad4d56aca189bf4fa18b8896f9ed4a5e5ddf618 
nvim-treesitter commit: #ea3a37a
neovim version: 10.0

following the instruction of this discussion: https://github.com/EmranMR/tree-sitter-blade/discussions/19#discussion-5400675

![image](https://github.com/user-attachments/assets/a1bb2225-e9b7-45a1-a4f4-15a642cb71ea)
![image](https://github.com/user-attachments/assets/27943a96-66fe-4b95-9c9d-b56f98a228a3)

Any suggestion?

**Comment by calebdw** [comment]
This is not a concern---if you toggle the language (`I`), you'll see that it is likely the `html` parser and can be ignored

**Comment by calebdw** [comment]
@dobrydev, I've already said this is a non-issue. This is in no way affecting you---you just see `ERROR` and are freaking out unnecessarily

**Comment by Th3Cod3** [comment]
@calebdw Thanks for the quick response! I initially thought the "Blade parser" extended the `html` parser to handle those tokens more gracefully. At the beginning of the file, it seemed to work as a Blade parser, but if you’re saying it can be ignored, that's fine. Thanks again!

![image](https://github.com/user-attachments/assets/771d5101-c220-498b-ae93-958e553e5019)

I’ll go ahead and close this issue, given that it's not an actual problem. Appreciate the guidance.

**Comment by calebdw** [comment]
@Th3Cod3, the "errors" are occurring because the blade parser simply injects `php` into those section 
(which in turn injects `html`). The html parser is throwing these errors because it's parsing the same text range but these "errors" can be ignored.
